map shift+enter send_text all \x1b[13;2u

macos_option_as_alt right

font_family      family='Dank Mono' postscript_name=DankMono-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
