[tools]
"aqua:1password/cli" = "v2.32.0"
"aqua:aws/aws-cli" = "latest"
"aqua:cli/cli" = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:xcp" = "latest"
"cargo:zellij" = "latest"
chezmoi = "latest"
go = "1.25"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
rust = "stable"
usage = "latest"
