[tools]
"aqua:1password/cli" = "v2.32.0"
"aqua:aws/aws-cli" = "latest"
"aqua:cli/cli" = "latest"
"aqua:pranshuparmar/witr" = "latest"
"cargo:ast-grep" = "latest"
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:difftastic" = "latest"
"cargo:du-dust" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fend" = "latest"
"cargo:hexyl" = "latest"
"cargo:hyperfine" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:xcp" = "latest"
"cargo:zellij" = "latest"
chezmoi = "latest"
fzf = "latest"
"github:bojanrajkovic/unquote" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:open-cli-collective/cpm" = "latest"
go = "latest"
"npm:@openai/codex" = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
node = "latest"
"npm:agent-browser" = "latest"
rust = "1.96.0"
usage = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"
fastfetch = "latest"
opentofu = "1.12.3"
ffmpeg = "latest"
python = "latest"
gcloud = "latest"
"github:googleworkspace/cli" = "latest"
"github:bojanrajkovic/crapify" = "latest"
"cargo:cargo-binstall" = "latest"
flyctl = "latest"
pnpm = "10.33.0"
duckdb = "latest"

[settings]
experimental = true
cargo.binstall = true
github.credential_command = "gh auth token"
