[tools]
"aqua:1password/cli" = "v2.32.0"
"aqua:aws/aws-cli" = "latest"
"aqua:cli/cli" = "latest"
"aqua:pranshuparmar/witr" = "latest"
"cargo:ast-grep" = "latest"
"cargo:bat" = "latest"
"cargo:bottom" = "latest"
"cargo:difftastic" = "latest"
"cargo:du-dust" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fend" = "latest"
"cargo:hexyl" = "latest"
"cargo:hyperfine" = "latest"
"cargo:ripgrep" = "latest"
"cargo:starship" = "latest"
"cargo:xcp" = "latest"
"cargo:zellij" = "latest"
chezmoi = "latest"
fzf = "latest"
go = "1.25"
"go:github.com/open-cli-collective/cpm/cmd/cpm" = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:agent-browser" = "latest"
rust = "stable"
usage = "latest"
uv = "latest"
yq = "latest"
yt-dlp = "latest"

[settings]
experimental = true
